print('hello world!')
print('Whay is your name?')
myname = input()
print('Hello, nice to meet you ' + myname)
print()
print('The length of your name is:')
print(len(myname))
print()
print('What is your age?')
myage = input()
print()
print('You will be ' + str(int(myage) + 1) + ' in a year.')